<script lang="ts" setup>
import { onBeforeMount, ref } from "vue";
import "./css/style.css";

import {
    AiResponseQuery,
    BpmnFile,
    BpmnFileQuery,
    DefaultPrompt,
    GetBpmnFilesCommand,
    GetPromptsCommand,
    LogErrorCommand,
    LogInfoCommand,
    MiranumCopilotQuery,
    PromptQuery,
} from "../../shared";
import { createResolver } from "@/utils";

import { initVsCodeApi, MissingStateError, VsCode } from "./vscode";
import SidebarMenu from "./components/SidebarMenu.vue";
import DefaultView from "@/views/DefaultView.vue";
import { DefaultViewState, getGlobalState, setGlobalState } from "@/state";

//
// Vars
//
// eslint-disable-next-line @typescript-eslint/naming-convention
declare const process: { env: { NODE_ENV: string } };

let vscode: VsCode;
if (process.env.NODE_ENV === "development") {
    vscode = initVsCodeApi("development");
} else {
    vscode = initVsCodeApi("production");
}

// The initial data send from the backend
const prompts = ref<Map<string, DefaultPrompt[]>>(new Map());
const bpmnFiles = ref<BpmnFile[]>([]);
// const templates = ref<Map<string, Template[]>>(new Map());

/* The prompt entered by the user. */
let userPrompt = ref("");
/* The response generated by the language model. */
let aiResponse = ref("");
/* The BPMN file selected by the user. */
let selectedBpmn = ref<BpmnFile | undefined>();

/* The current view. */
const viewState = ref("DefaultView");
/* Whether the webview is loading. */
const loading = ref(true);
/* Whether the sidebar is shrunk. */
let shrunk = ref(false);

//
// Logic
//

const promptsResolver = createResolver<Map<string, DefaultPrompt[]>>();
const bpmnFilesResolver = createResolver<BpmnFile[]>();
// const templateResolver = createResolver<Map<string, Template[]>>();

/**
 * The "main" method.
 * We wait until the webview is fully loaded.
 * Then we send a message to the backend to inform that it is fully loaded.
 * The backend will send then the initial data.
 */
onBeforeMount(async () => {
    // Add event listener for incoming messages
    window.addEventListener("message", receiveMessage);

    try {
        const state = vscode.getState("DefaultViewState"); // Throws MissingStateError if no state is available

        vscode.postMessage(new GetBpmnFilesCommand());
        vscode.postMessage(new GetPromptsCommand());

        const [bpmnFilesData, promptsData] = [
            await bpmnFilesResolver.wait(),
            await promptsResolver.wait(),
        ];

        bpmnFiles.value = bpmnFilesData ?? [];
        prompts.value = promptsData ?? new Map();
        userPrompt.value = state.currentPrompt;
        aiResponse.value = state.aiResponse;
        selectedBpmn.value = state.selectedBpmnFile;

        state.bpmnFiles = bpmnFilesData ?? [];
        state.prompts = promptsData ?? new Map();
        setGlobalState(state);

        loading.value = false;
    } catch (error) {
        if (error instanceof MissingStateError) {
            vscode.postMessage(new GetBpmnFilesCommand());
            vscode.postMessage(new GetPromptsCommand());

            const [bpmnFilesData, promptsData] = [
                await bpmnFilesResolver.wait(),
                await promptsResolver.wait(),
            ];

            console.debug("[Debug] Initial data received", bpmnFilesData, promptsData);

            loading.value = false;

            const newState = new DefaultViewState();
            newState.bpmnFiles = bpmnFilesData ?? [];
            newState.prompts = promptsData ?? new Map();

            setGlobalState(newState);
            vscode.setState(newState);

            postMessage(new LogInfoCommand("Webview was initialized."));
        } else {
            const message = error instanceof Error ? error.message : `${error}`;
            postMessage(new LogErrorCommand(message));
        }
    }
});

/**
 * Handle incoming messages.
 * @param message The incoming message
 */
function receiveMessage(message: MessageEvent<MiranumCopilotQuery>): void {
    const query = message.data;

    console.debug("[Debug] receiveMessage", query);

    switch (true) {
        case query.type === "BpmnFileQuery": {
            const bpmnFileQueryData = (query as BpmnFileQuery).bpmnFiles;
            bpmnFiles.value = bpmnFileQueryData;
            bpmnFilesResolver.done(bpmnFileQueryData);
            break;
        }
        case query.type === "PromptQuery": {
            const promptQueryData = new Map<string, DefaultPrompt[]>(
                JSON.parse((query as PromptQuery).prompts),
            );
            prompts.value = promptQueryData;
            promptsResolver.done(promptQueryData);
            break;
        }
        case query.type === "AiResponseQuery": {
            const state = getGlobalState();
            userPrompt.value = state.currentPrompt;
            aiResponse.value = (query as AiResponseQuery).response;
            state.aiResponse = aiResponse.value;
            vscode.setState(state);
            break;
        }
    }
}

function handleSidebarToggle(isVisible: boolean) {
    shrunk.value = isVisible;
}

function handleSelectedPrompt(prompt: DefaultPrompt) {
    viewState.value = "DefaultView";
    userPrompt.value = prompt.prompt;

    const state = getGlobalState();
    state.currentPrompt = userPrompt.value;
    vscode.setState(state);
}
</script>

<template>
    <main :class="{ shrunk: shrunk }">
        <DefaultView
            v-if="viewState === 'DefaultView'"
            :ai-response="aiResponse"
            :bpmn-files="bpmnFiles"
            :loading="loading"
            :prompt="userPrompt"
        />
    </main>
    <SidebarMenu
        :prompts="prompts"
        @sidebar-toggled="handleSidebarToggle"
        @prompt-selected="handleSelectedPrompt"
    />
</template>

<style scoped>
main {
    display: grid;
    grid-template-areas:
        "input"
        "output";
    gap: 40px;

    max-width: 800px;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}
</style>
